"""urls_table

Revision ID: 3952a2f5fd71
Revises:
Create Date: 2023-03-12 22:06:33.402235

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3952a2f5fd71"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("url_hash", sa.String(length=10), nullable=False),
        sa.Column("short_url", sa.String(), nullable=False),
        sa.Column("target_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("url_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("urls")
    # ### end Alembic commands ###
