# type: ignore
"""init1

Revision ID: eabac535fdb1
Revises:
Create Date: 2023-09-16 18:05:13.070738

"""
import sqlalchemy as sa

from alembic import op
from src.db.models import Base

# revision identifiers, used by Alembic.
revision = "eabac535fdb1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.sql.ddl.CreateSequence(
            sa.Sequence(
                "id_seq",
                metadata=Base.metadata,
                start=1,
                increment=1,
                data_type=sa.BIGINT,
            ),
            if_not_exists=True,
        )
    )
    op.create_table(
        "urls",
        sa.Column("url_hash", sa.String(length=20), nullable=False),
        sa.Column("target_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("url_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.sql.ddl.DropSequence(
            sa.Sequence(
                "id_seq",
                metadata=Base.metadata,
                start=1,
                increment=1,
                data_type=sa.BIGINT,
            ),
            if_not_exists=True,
        )
    )
    op.drop_table("urls")
