name: Lint
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run black check
        uses: psf/black@stable
        with:
          options: "--check --line-length=79"
          src: "./src"
          version: "~= 22.0"
      - name: Run isort check
        uses: isort/isort-action@master
        with:
          configuration: "--check --profile=black --line-length=79"
